#!/bin/bash
#~ set -x
#~ exec 2>>/home/samir/log_vlc.txt
#cd `pwd`
tport=4213

if [ $1 = "-p" ] || [ $1 = "--port" ]
then
    tport=$2
    shift 2
fi


run(){
	/bin/sh -c "echo \"admin\n$*\"; sleep 0.1; echo \"logout\"" | nc 127.0.0.1 $tport | sed '/Password:/d' | 
	sed '/VLC media player 2.0.3 Twoflower/d' |
	sed '/Welcome, Master/d' |
	sed '/Bye-bye/d'
}
if [[ $1 = "pause" ]]; then
	a=`run is_playing`;
	a=${a:0:1}
	if [ $a -le 0 ]; then
		run play
		exit 0
	fi;
fi;

 if [[ $1 = "add" ]] || [[ $1 = "enqueue" ]]; then
	if [ `pidof vlc | wc -l` -le 0 ]; then
		vlc --extraintf telnet --telnet-port $tport &>/dev/null &
		sleep 1
		if [ `pidof vlc | wc -l` -le 0 ]; then
			cvlc --extraintf telnet --telnet-port $tport &>/dev/null &
			sleep 1
		fi
	fi
	i=0
	for path in "${@:2}"; do
		c=${path:0:1}
		d=${path:0:6}
		if [[ "$c" != "/" ]] && [[ "$d" != "http:/" ]] && [[ "$d" != "ftp://" ]]; then
			run $1 "`pwd`/$path"
		else
			run $1 $path
		fi;
	done
	exit 0
fi;

if [[ $1 = "goto" ]] || [[ $1 = "playlist" ]]; then
  c=${2/ */} # supprime tout après un espace insécable
  run $1 $c
  exit 0
fi
	

run $*;

