#!/bin/bash
##############################################################
#              Configuration par defaut                      #
#                                                            #
# À surcharger possiblement dans ~/.config/vrun/configrc     #
##############################################################


# port telnet de vlc
tport=4212
# mot de passe telnet de vlc
password="admin"

#############################################################

if [ -f ~/.config/vrun/configrc ]; then
. ~/.config/vrun/configrc
fi

if [[ $1 = "-p" ]] || [[ $1 = "--port" ]]
then
    tport=$2
    shift 2
fi


run(){
	/bin/sh -c "echo \"$password\n$*\"; sleep 0.1; echo \"logout\"" | nc 127.0.0.1 $tport | 
	sed '/Password:/d;/VLC media player .*/d;/Welcome, Master/d;/Bye-bye/d'
}

contain(){
    local i
    for i in $2; do
        if [[ "$i" = "$1" ]]; then
            return 0
        fi
    done
    return 1
}

second_to_time(){
    local min seconde
    if [ $1 -ge 60 ]; then
        min=$(( $1 / 60 ))
        echo -n "${min}:"
    else
        min=0;
    fi
    seconde=$(( $1 - 60 * $min ))
    printf "%02d\n" $seconde
}

case $1 in
	get_time|get_length)
		a=`run $1`
		a=${a%?}
		if [[ $a = [0-9]* ]]; then
			second_to_time $a;
		fi
	;;
	pause)
		a=`run is_playing`;
		a=${a:0:1}
		if [ $a -le 0 ]; then
			run play
                else
                        run pause
		fi
	;;
	add|enqueue)
		i=0
		for path in "${@:2}"; do
			c=${path:0:1}
			d=${path:0:6}
			if [[ "$c" != "/" ]] && [[ "$d" != "http:/" ]] && [[ "$d" != "ftp://" ]]; then
				run $1 "`pwd`/$path"
			else
				run $1 $path
			fi;
		done
	;;
	goto|playlist|atrack|vtrack|vratio|vcrop|crop|vzoom|zoom|vdeinterlace|vdeinterlace_mode|vdeinterlace_mode)
		c=${2/ */} # supprime tout après un espace insécable
		run $1 $c
	;;
	move)
		c=${2/ */}
		d=${3/ */}
		run $1 $c $d
	;;
	delete)
		for file in "${@:2}"; do
			c=${file/ */} # supprime tout après un espace insécable
			run $1 $c
		done
	;;
	start)
		if [ `pidof vlc | wc -l` -le 0 ]; then
			shift
			vlc --extraintf telnet --telnet-port $tport $@ &>/dev/null &
			sleep 2
			if [ `pidof vlc | wc -l` -le 0 ]; then
				cvlc --extraintf telnet --telnet-port $tport $@ &>/dev/null &
				sleep 2
			fi
		fi
	;;
	*)
		run $*;
	;;
esac
