#!/bin/bash
##############################################################
#              Configuration par defaut                      #
#                                                            #
# À surcharger possiblement dans ~/.config/vrun/configrc     #
##############################################################


# port telnet de vlc
tport=4212
# mot de passe telnet de vlc
password="admin"

#############################################################

if [ -f ~/.config/vrun/configrc ]; then
. ~/.config/vrun/configrc
fi

if [[ $1 = "-p" ]] || [[ $1 = "--port" ]]
then
    tport=$2
    shift 2
fi


run(){
	/bin/sh -c "echo \"$password\n$*\"; sleep 0.1; echo \"logout\"" | nc 127.0.0.1 $tport | 
	sed '/Password:/d;/VLC media player .* Twoflower/d;/Welcome, Master/d;/Bye-bye/d'
}

contain(){
    local i
    for i in $2; do
        if [[ "$i" = "$1" ]]; then
            return 0
        fi
    done
    return 1
}

second_to_time(){
    local min seconde
    if [ $1 -ge 60 ]; then
        min=$(( $1 / 60 ))
        echo -n "${min}:"
    else
        min=0;
    fi
    seconde=$(( $1 - 60 * $min ))
    printf "%02d\n" $seconde
}

echo -en '\033['m;

if contain "$1" "get_time get_length"; then
    a=`run $1`
    a=${a:0:-1}
    if [[ $a = [0-9]* ]]; then
        second_to_time $a;
        exit 0
    fi;
fi;

if [[ $1 = "pause" ]]; then
	a=`run is_playing`;
	a=${a:0:1}
	if [ $a -le 0 ]; then
		run play
		exit 0
	fi;
fi;

 if contain "$1" "add enqueue"; then
	if [ `pidof vlc | wc -l` -le 0 ]; then
		vlc --extraintf telnet --telnet-port $tport &>/dev/null &
		sleep 1
		if [ `pidof vlc | wc -l` -le 0 ]; then
			cvlc --extraintf telnet --telnet-port $tport &>/dev/null &
			sleep 1
		fi
	fi
	i=0
	for path in "${@:2}"; do
		c=${path:0:1}
		d=${path:0:6}
		if [[ "$c" != "/" ]] && [[ "$d" != "http:/" ]] && [[ "$d" != "ftp://" ]]; then
			run $1 "`pwd`/$path"
		else
			run $1 $path
		fi;
	done
	exit 0
fi;

if [[ $1 = "goto" ]] || [[ $1 = "playlist" ]]; then
  c=${2/ */} # supprime tout après un espace insécable
  run $1 $c
  exit 0
fi

run $*;

